# -*- coding: utf-8 -*-
"""NameGenderCSVtoRedshift - Simple ETL with Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdWdT8OfE81Wr5Nh6IGditiyJ2UgTe7Y

### **Define ETL functions**

###### Extract function
"""

import requests

def extract(url):
    f = requests.get(url)
    print(f)
    return (f.text)

"""##### Transform function

"""

import csv

def transform(data):
    reader = csv.reader(data.strip().split("\n"))
    return reader

"""##### Redshift connection function"""

import psycopg2

# Redshift connection function
def get_Redshift_connection():
    host = "ssde.cnqux5xggmn5.us-east-2.redshift.amazonaws.com"
    redshift_user = "choyoura"
    redshift_pass = "password"
    port = 5439
    dbname = "dev"

    conn = psycopg2.connect("dbname={dbname} user={user} host={host} password={password} port={port}".format(
        dbname=dbname,
        user=redshift_user,
        password=redshift_pass,
        host=host,
        port=port
    ))

    conn.set_session(autocommit=True)
    return conn.cursor()

"""##### Load function



"""

# try/except, autocommit = TRUE
def load(csv_reader):
    cur = get_Redshift_connection() 
    try:
      sql = """BEGIN;CREATE TALBE IF NOT EXISTS choyoura.name_gender (
              name varchar(64),
              gender varchar(16)
              );
              DELETE FROM choyoura.name_gender;"""
      cur.execute(sql)   
      for name, gender in csv_reader:
        sql = """
              INSERT INTO choyoura.name_gender
              VALUES ({name}, {gender});
              """.format(name=name, gender=gender)
        cur.execute(sql)
      cur.execute("END") # cur.execute("COMMIT")

    except Exception as e:
      cur.execute("ROLLBACK")  

    finally:
      # if conn.is_connected():
      cur.close()

"""##### Logging Function"""

from datetime import datetime

def log(message):
    timestamp_format = '%Y-%h-%d-%H:%M:%S' # Year-Monthname-Day-Hour-Minute-Second
    now = datetime.now() # get current timestamp
    timestamp = now.strftime(timestamp_format)
    with open("logfile.txt","a") as f:
        f.write(timestamp + ',' + message + '\n')

"""### **Run the ETL Process**



"""

link = "https://s3-geospatial.s3-us-west-2.amazonaws.com/name_gender.csv"

data = extract(link)
csv_reader = transform(data)
load(csv_reader)

# !pip install sqlalchemy==1.3.2

import sqlalchemy

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

# %sql postgresql://choyoura:Choyoura!1@ssde.cnqux5xggmn5.us-east-2.redshift.amazonaws.com:5439/dev

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# select * from choyoura.name_gender limit 20;